name: flutter_extension
description: "Flutter extension"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  shared_preferences:
  flutter_screenutil:
  flutter_svg:
  flutter_spinkit:
  cached_network_image:
  shimmer: 
  iconly: ^1.0.1
  zoom_tap_animation: ^1.1.0
  google_fonts: ^8.0.0
  file_picker: ^10.3.10
  video_player: ^2.10.1
  percent_indicator: ^4.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
